---
- name: Deploy Java App
  hosts: all
  become: yes

  tasks:
    - name: Installing Docker 
      apt:
        name: 
          - docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "ajmer1705/gitjava:latest"
        source: pull

        
    - name: Create Web Java Docker container
      community.docker.docker_container:
        name: onlinebookstore
        image: "ajmer1705/gitjava:latest"
        state: started
        ports:
          - "80:8080"

