name: Build and Deploy Java App

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        env:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ env.password }} | docker login -u ${{ env.username }} --password-stdin

      - name: Build the docker image
        run: |
          docker build . -t ajmer1705/gitjava:latest -f Docker-files/app/Dockerfile

          
      - name: push Docker image
        run: |
          docker push ajmer1705/gitjava:latest













# name: Build and Deploy Flask App

# on: 
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set Up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
          
#       # - name: Run Tests (if any)
#       #   run: pytest tests

#       - name: Run Flask App
#         run: |
#           python script.py
#           # Assuming the Flask app generates a file 'result.txt'
#           echo "This is the result" > result.txt
      
#       - name: Upload Result
#         uses: actions/upload-artifact@v2
#         with:
#           name: my-artifact
#           path: result.txt
