name: Test Ansible Playbook

on:
  workflow_run:
    workflows: ["Build and Deploy Java App"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Install Ansible
        run: |
          sudo apt-get purge ansible
          sudo apt-get autoremove
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt install ansible
          
      - name: Deploy with Ansible
        run: ansible-playbook -i ip.txt -u "azureuser" --private-key ~/.ssh/id_rsa ansible-playbook.yml
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: False
